name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PlatformIO Core
        run: |
          python3 -m pip install --upgrade pip
          pip3 install platformio

      - name: Install Micro_ROS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
          sudo apt-get install -y python3-pip
          python3 -m pip install catkin_pkg lark-parser empy

      - name: Install PlatformIO project dependencies
        run: |
          pio update
          pio lib install
          pio pkg install

      - name: Build PlatformIO Project
        run: pio run

